export enum NotificationType {
  TICKET_ACCEPTED = 'TICKET_ACCEPTED',
  TICKET_REFUSED = 'TICKET_REFUSED',
  TICKET_ASSIGNED = 'TICKET_ASSIGNED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  TICKET_CREATED = 'TICKET_CREATED',
  REPORT_ADDED = 'REPORT_ADDED'
} 